class AddProducts < ActiveRecord::Migration[5.2]
  def change
    Product.create :title => 'Chicken Hawaii', :name => 'chicken_hawaii', :description => 'Pizza crust is layered with smokey bbq sauce, chicken pieces, creamy mozzarella, sweet pineapple, and flavorful red onion and cilantro', :price => 18, :size => 16, :is_spicy => false, :is_veg => false, :is_best_offer => false, :path_to_image => '/images/chicken_hawaii.jpg', :path_to_big_image => '/images/chicken_hawaii_big.jpg', :path_to_page => '/pizzas/chicken_hawaii'
    Product.create :title => 'Primo Meat', :name => 'primo_meat', :description => 'Mouth watering pepperoni, cabanossi, mushroom, capsicum, black olives and stretchy mozzarella', :price => 15, :size => 16, :is_spicy => true, :is_veg => false, :is_best_offer => false, :path_to_image => '/images/primo_meat.jpg', :path_to_big_image => '/images/primo_meat_big.jpg', :path_to_page => '/pizzas/primo_meat'
    Product.create :title => 'Vegge Lover', :name => 'vegge_lover', :description => 'Extra-virgin olive oil, garlic, mozzarella cheese, onions, mushrooms, green olives, black olives, fresh tomatoes', :price => 12, :size => 16, :is_spicy => false, :is_veg => true, :is_best_offer => false, :path_to_image => '/images/vegge_lover.jpg', :path_to_big_image => '/images/vegge_lover_big.jpg', :path_to_page => '/pizzas/vegge_lover'
    Product.create :title => 'Italiano Original', :name => 'italiano_original', :description => 'Ricotta, sun dried tomatoes, garlic, mozzarella cheese, topped with lightly drizzled red sauce, pesto, and fresh basil', :price => 14, :size => 16, :is_spicy => false, :is_veg => false, :is_best_offer => true, :path_to_image => '/images/italiano_original.jpg', :path_to_big_image => '/images/italiano_original_big.jpg', :path_to_page => '/pizzas/italiano_original'
    Product.create :title => 'Trio Cheese', :name => 'trio_cheese', :description => 'Mouth watering pepperoni, cabanossi, mushroom, capsicum, black olives and stretchy mozzarella', :price => 12, :size => 16, :is_spicy => false, :is_veg => false, :is_best_offer => true, :path_to_image => '/images/trio_cheese.jpg', :path_to_big_image => '/images/trio_cheese_big.jpg', :path_to_page => '/pizzas/trio_cheese'
    Product.create :title => 'Pepperoni', :name => 'pepperoni', :description => 'Pepperoni Pizza - Extra-virgin olive oil, garlic, mozzarella cheese, onions, mushrooms, green olives, black olives, fresh tomatoes', :price => 18, :size => 16, :is_spicy => true, :is_veg => false, :is_best_offer => false, :path_to_image => '/images/pepperoni.jpg', :path_to_big_image => '/images/pepperoni_big.jpg', :path_to_page => '/pizzas/pepperoni'
    Product.create :title => 'Pepperoni Calzone', :name => 'pepperoni_palzone',:description => 'Piled with shrimp, calamari, clams, mussels, surimi and stretchy mozzarella, seasoned with tangy lemon pepper', :price => 12, :size => 16, :is_spicy => false, :is_veg => true, :is_best_offer => true, :path_to_image => '/images/pepperoni_calzone.jpg', :path_to_big_image => '/images/pepperoni_calzone_big.jpg', :path_to_page => '/pizzas/pepperoni_calzone'
    Product.create :title => 'Summer', :name => 'summer', :description => 'Shrimp, Red Capsicum, Green Capsicum, Onion, Chilli flakes, Lemon Pepper, Mozzarella, finished with Aioli', :price => 15, :size => 16, :is_spicy => false, :is_veg => true, :is_best_offer => true, :path_to_image => '/images/summer.jpg', :path_to_big_image => '/images/summer_big.jpg', :path_to_page => '/pizzas/summer'
    Product.create :title => 'Grand Italiano', :name => 'grand_italiano', :description => 'An easy homemade pizza dough is topped with vine-ripened tomatoes, sharp arugula, olive oil, garlic and fresh mozzarella', :price => 20, :size => 16, :is_spicy => false, :is_veg => true, :is_best_offer => true, :path_to_image => '/images/grand_italiano.jpg', :path_to_big_image => '/images/grand_italiano_big.jpg', :path_to_page => '/pizzas/grand_italiano'
  end
end
